version: '3.7'

services:
  # See:
  # https://hub.docker.com/r/bitnami/zookeeper
  zookeeper:
    image: bitnami/zookeeper:latest
    hostname: streams-zookeeper
    container_name: streams-zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  # See:
  # https://hub.docker.com/r/bitnami/kafka
  kafka:
    image: bitnami/kafka:latest
    hostname: streams-kafka
    container_name: streams-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper